### ISSUE TITLE
Redirect to original domain if SSL / https

### ISSUE THREAD

**Issue by metuza** [straube/multiple-domain#11]
Installed plugin in my woocommerce test site which is not using SSL and everything seems to work perfect. Then i did the same install in my live site which is using SSL and then i get a 301 redirect back to original domain.

It works ok if i use domain without www in browser.

Also hreflang tags is not correct, missing ://
<link rel="alternate" hreflang="httpswww.arctic-fritid.no/" href="x-default"/><link rel="alternate" hreflang="httpsarctic-fritid.se/" href="nb-SE"/>

Any idea?

**Comment by metuza** [comment]
I did find the issue.. Several places the WWW was not cleaned out from domain and this caused a redirect to the old domain.

I added preg_replace( '/^www\./i', '', $value ); around where needed and now everything works ok. Also fixed the hreflang $_SERVER['HTTPS'] ? 'http://' : 'https://';

So at my end it works perfect now.

**Comment by straube** [comment]
Hey @metuza. Do you think this is a bug or something specifically related to your setup? If it's a bug, could you explain better what you changed and maybe submit a pull request to fix it? Thanks!

**Comment by metuza** [comment]
I think it is a bug.. The construct function in code does not clean out WWW from domain so when compared with stored custom domains it is ofcourse not found and standard domain is used.

Here i have added preg_replace to remove WWW, so one step further.

`public function __construct()
    {
        $ignoreDefaultPort = true;
        $headerHost = filter_input(INPUT_SERVER, 'HTTP_X_HOST', FILTER_DEFAULT, [
            'options' => [
                'default'=> filter_input(INPUT_SERVER, 'HTTP_HOST'),
            ],
        ]);
        if (!empty($headerHost)) {
            $domain = preg_replace( '/^www\./i', '', $headerHost );
            $matches = [];
            if (preg_match('/^(.*):(\d+)$/', $domain, $matches) && $this->isDefaultPort($matches[2])) {
                $domain = $matches[1];
            }
            $this->domain = $domain;
        }
        $this->domains = get_option('multiple-domain-domains');
        if (!is_array($this->domains)) {
            $this->domains = [];
        }
        $this->originalDomain = $this->getDomainFromUrl(get_option('home'), $ignoreDefaultPort);
        if (!array_key_exists($this->domain, $this->domains)) {
            $this->domain = preg_replace( '/^www\./i', '', $this->originalDomain );
        }
    }`

Then vi have the same issue here, also added preg_replace and now it works great:
`private function getDomainFromUrl($url, $ignoreDefaultPort = false)
    {
        $parts = parse_url($url);
        $domain = $parts['host'];
        if (!empty($parts['port']) && !($ignoreDefaultPort && $this->isDefaultPort($parts['port']))) {
            $domain .= ':' . $parts['port'];
        }
        return preg_replace( '/^www\./i', '', $domain );
    }`

Then a bug with hreflang tags, fixed by adding :// into the check:
`public function addHrefLangHeader()
    {
        $uri = $_SERVER['REQUEST_URI'];
        $protocol = !isset($_SERVER['HTTPS']) || 'off' == $_SERVER['HTTPS'] ? 'http://' : 'https://';
        $this->outputHrefLangHeader($protocol . $this->originalDomain . $uri);

        foreach ($this->domains as $key => $values) {
            if (is_array($values) && !empty($values['lang'])) {
                $url = $key . $values['base'] . $uri;
                /*
                 * Prepend the current protocol if none is set.
                 */
                if (!preg_match('/https?:\/\//', $values['base'])) {
                    $url = $protocol . $url;
                }
                $this->outputHrefLangHeader($url, $values['lang']);
            }
        }
    }`

Tested with SSL, with/without WWW and using subdomains. Works great.

**Comment by straube** [comment]
Thanks for the info. Unfortunately, I won't be able to write a patch for the next 2 weeks. I let you know as soon as I update the plugin.

**Comment by metuza** [comment]
No problems, it works for me now.. Maybe you at the same time should consider a way to add CDN url so we also could use CDN for the secondary domain.
