### ISSUE TITLE
Remove filter_input from plugin

### ISSUE THREAD

**Issue by straube** [straube/multiple-domain#14]
From [this discussion](https://wordpress.org/support/topic/replace-filter_input-in-plugin-construct/) on WP.org support forum:

> According to numerous reports filter_input(INPUT_SERVER…) on PHP with CGI/FastCGI might result in NULL being returned.
> This happened to me recently and as such plugin’s constructor was assigning
> 
>     $this->domain = $this->originalDomain;
>
> which results in home page always redirecting to original domain.
> 
> Could you please fix it and use normal $_SERVER variables to determine domain instead of filter_input function?
> 
> Read comment from “anthony dot parsons at manx dot net” here for some details: http://php.net/manual/en/function.filter-input.php or google for ‘filter_input INPUT_SERVER returns null’ for bug confirmation.

**Comment by QuietNoise** [comment]
Hi,

When you plan to implement it?

**Comment by straube** [comment]
Hi @QuietNoise,

Despite my effort to keep the plugin up to date and bug-free, I was really busy in the last months. I didn't start working on this issue. It sure requires some testing, but it doesn't seem a complex one at a first glance. If you could spare the project a couple hours, feel free to submit a PR. I really appreciate that. :)
