### ISSUE TITLE
Plugin doesn't work after update

### ISSUE THREAD

**Issue by tbrandysky** [straube/multiple-domain#19]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /srv/wordpress/webpage/wp-content/plugins/multiple-domain.disabled/multiple-domain.php on line 411

**Comment by straube** [comment]
Hello @tbrandysky, what PHP version are you using?

The error you got is in this line:

    register_activation_hook(__FILE__, [ MultipleDomain::class, 'activate' ]);

I'm wondering if the problem is due to the `MultipleDomain::class`. That was added on [PHP 5.5](http://php.net/releases/5_5_0.php).

**Comment by tbrandysky** [comment]
This is Wordpress running in our production environment on Centos 7 (CentOS Linux release 7.4.1708 (Core) with php-5.4.16-43.el7_4.1.x86_64

**Comment by straube** [comment]
Yea, as I supposed you're using an older PHP version. I'll release an update by the end of the day to make it compatible with PHP 5.4 again.

If you can't wait that long, please update the line 411 this way:

    register_activation_hook(__FILE__, [ 'MultipleDomain', 'activate' ]);

**Comment by tbrandysky** [comment]
Great, 
thank you very much for your work !
I can wait for the update.

**Comment by straube** [comment]
@tbrandysky I've just released a new version, 0.7.1. Please update your installation and let me know if it fix the issue.

**Comment by tbrandysky** [comment]
I can confirm the issue is solved in new version.
Thank you very much for quick fix !
