### ISSUE TITLE
Possible XSS issue

### ISSUE THREAD

**Issue by rasmustaarnby** [straube/multiple-domain#28]
Hi, 

We ran a security test on a site which uses this plugin and it flagged a possible XSS issue with an alternate header. We tracked it to this line https://github.com/straube/multiple-domain/blob/master/multiple-domain/MultipleDomain.php#L383

**Comment by straube** [comment]
@rasmustaarnby Thanks for reporting that. This is now fixed on `master` and will be available with the next release (1.0.0, probably).
