### ISSUE TITLE
Don't add SSL when accessing via a Tor domain name

### ISSUE THREAD

**Issue by TheFiZi** [straube/multiple-domain#31]
I'm using this plugin to get my blog working as a Tor hidden service. My site is available via it's normal URL and a tor service URL.

The base domain is: https://www.pickysysadmin.ca/ and Wordpress enforces SSL

This is my configuration for the plugin:

![image](https://user-images.githubusercontent.com/1762426/48307989-f60a3600-e50d-11e8-8127-b56d80d4a019.png)

When I go to http://27i7rsfkhoanzabw.onion/ the initial page load is fine. When I click on any internal links to the site the URL is re-written to http**s**://27i7rsfkhoanzabw.onion/ which doesn't work in Tor land.

A potential solution to this would be to have the plugin always drop/not add SSL on domains that end in .onion when re-writing the URLs.

**Comment by straube** [comment]
@TheFiZi I'm wondering if it makes sense to have this exception hard-coded.

I may add a new option for when adding a domain:

```
[ Name ][ Protocol (Auto, Force HTTP, or Force HTTPS) ][ Base path ][ Locale ]
```

I think that makes more sense and covers more cases where users want to force a given protocol. What do you think?

In any way, I only will have time to work on this change in 2-3 weeks.

**Comment by TheFiZi** [comment]
@straube That sounds like a good way to handle it to me.

**Comment by straube** [comment]
I started working on this. I had a discussion with our UX designer and we'll improve the usability of the plugin configuration section.

**Comment by straube** [comment]
@TheFiZi I added the protocol option to domain settings. Please update the plugin in your WP installation to `0.10.0` and set the protocol option for `27i7rsfkhoanzabw.onion` to `http://`. Let me know if that fixes the issue.

**Comment by TheFiZi** [comment]
Hmmm. I don't think it's re-writing the URLs at all now.

![image](https://user-images.githubusercontent.com/1762426/54060919-63c02900-41b3-11e9-8b5e-e367632dcb1e.png)

**Comment by straube** [comment]
Could you send me a screenshot of your current plugin setup?

**Comment by TheFiZi** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/1762426/54148774-1382da00-43f2-11e9-83b2-cd9fbc61addf.png)

**Comment by straube** [comment]
I just pushed an update (0.10.2) to fix that. Until 0.9.x, you were not required to include the original domain where you installed WordPress into the plugin settings. However, in 0.10.0 this is mandatory. That requirement broke some installations. I added a fallback to the plugin always load the original domain. Which is `www.pickysysadmin.ca` in your case, right?

Please keep me posted about any remaining issues.

**Comment by TheFiZi** [comment]
Looks like that patch did the trick and got us 98% there.

Post patch: 
![image](https://user-images.githubusercontent.com/1762426/54155903-4cc34600-4402-11e9-84ac-f399fe682ee9.png)

After loading up the site in Tor: 
![image](https://user-images.githubusercontent.com/1762426/54155927-577ddb00-4402-11e9-89ca-58ac42105e65.png)

Looks like only two images aren't having their URLs re-written. Those two images are linked inside a Widget block: 
![image](https://user-images.githubusercontent.com/1762426/54155997-81cf9880-4402-11e9-85f1-338ba633a17b.png)

That link to the "tip jar" is also not being re-written (pictured above): `<p><a title="More ways to tip with crypto" href="https://www.pickysysadmin.ca/the-tip-jar">More ways to tip with crypto</a></p>`
