### ISSUE TITLE
Missing locales on language list

### ISSUE THREAD

**Issue by straube** [straube/multiple-domain#38]
As reported by Tom, through email:

> I've started using your plugin but have trouble finding DE_AT in the list of locales. I figured that your plugin is using the wordpress translation list but that one isn't complete.
> 
> I change the value manually in the db but that didn't stick because the plugin didn't pull that new value into the domains list. Any unrelated change on the settings page would thus overwrite my changed setting :(

I believe that using the [language list](https://raw.githubusercontent.com/umpirsky/language-list/master/data/en/language.json) he suggested is the best approach here.

This issue was introduced by #17.

**Comment by TomK32** [comment]
Thanks, but it seems I've sent you the wrong link, it should be the locales list from this one:

https://github.com/umpirsky/locale-list/blob/master/data/en/locales.csv

As a simple litmus test: It has to be en_GB, not en_UK. https://support.google.com/webmasters/answer/189077?hl=en

**Comment by straube** [comment]
@TomK32 This was fixed by f1305ba. The latest release (v 0.8.5) includes that update.

Let me know if you find anything wrong with that update.

**Comment by TomK32** [comment]
Did the format change from de-DE to de_DE or something like that? Getting empty fields here when I load the preferences page. Might confuse a lot of people.

I strongly recommend adding the existing value to the select and no rely on it being in the list.

![2019-01-18 19 14 22](https://user-images.githubusercontent.com/3527/51404998-5d1f1900-1b55-11e9-9975-a7821b40a7dc.png)

**Comment by straube** [comment]
That sounds like a bug. Reopening the issue...

**Comment by straube** [comment]
@TomK32 I didn't run all the tests but this commit I referenced above contains a possible fix for this issue. After I do some more testing, I'll release an update through Wordpress' repository.

**Comment by straube** [comment]
@TomK32 I finally release an update to WP.org that includes the fix I mentioned last week. It's in 0.8.7. Let me know if it fixes the lang selection.
