### ISSUE TITLE
Problems with accessing wp-admin from multiple domains

### ISSUE THREAD

**Issue by tbrandysky** [straube/multiple-domain#39]
After last update we can't access /wp-config from other than primary WP domain. When wp-config is accessed from different domains (different_wp_domain.com/wp-config) it gets redirect to main WP domain (main_wp_domain.com/wp-config). 

Because we use one domain for external access to WP (wp-config is blocked here) and different domain to access WP internally this is a serious issue.

**Comment by straube** [comment]
Hey @tbrandysky. Thanks for reporting that. I'm aware of some admin issues on the latest 2 releases (0.8.4 and 0.8.5). I was trying to fix an issue in the General settings page and it ended up causing some undesired side effects. I'll rollback those changes in the next release. I'm busy with other projects right now but I'll try to do that ASAP. Thanks for your patience.

**Comment by straube** [comment]
@tbrandysky The latest release (0.8.6) should address this issue. Let me know in case you still see any unexpected behavior.

**Comment by tbrandysky** [comment]
I can confirm the issue is fixed in latest release. Thank you!
