### ISSUE TITLE
Error after install plugin, cant activate

### ISSUE THREAD

**Issue by adminjason** [straube/multiple-domain#4]
Parse error: syntax error, unexpected '[' in /www/wordpress/wp-content/plugins/multiple-domain/multiple-domain.php on line 62

**Comment by straube** [comment]
Hey @adminjason, you're probably using an old PHP version. Creating arrays using square brackets is only available starting at PHP 5.4. I advise you to upgrade your PHP version if possible, mainly for security reasons.

Let me know if something else is causing the issue.
