### ISSUE TITLE
Add canonical tags for SEO purposes

### ISSUE THREAD

**Issue by straube** [straube/multiple-domain#42]
Based on [this discussion in WordPress](https://wordpress.org/support/topic/does-the-plugin-work-well-with-yoast-seo/) forum, a nice addition to the plugin would be an option to add canonical tags to a site using Multiple Domain plugin.

This probably should be an option and not added by default. Site admins would have the choice to enable it and also pick one of the domains as the "primary" domain.

**Comment by iparker** [comment]
I'm not a seo expert but I think this is a good idea.

On my site currently every post/site has a canonical link to itself in head, for example

<link rel="canonical" href="https://gastrojobs.online/job/messehosts-messehostessen-fuer-die-ids-in-koeln-gesucht-12-16-03-briefing-11-03-2026/" />

On the secondary/additional domains this link should lead to the main domain. Just the main domain should have this link to itself.

And thats it. As described in https://moz.com/learn/seo/duplicate-content or https://moz.com/learn/seo/duplicate-content this should solve potential problems.

What do you think about this? I think this would be a very important feature?

**Comment by iparker** [comment]
And one additional idea: If no one of the multiple domains is marked as primary domain the "original" domain could be the fallback primary domain.
