### ISSUE TITLE
Domain not replaced for site_url  etc.

### ISSUE THREAD

**Issue by kokers** [straube/multiple-domain#43]
Hi!

Last update broke replacing urls. The condition in "replaceDomain" is never met cause "option_home" and other strictly url filters hasn't been replaced and can't get passed this:
https://github.com/straube/multiple-domain/blob/master/multiple-domain/MultipleDomain.php#L675
Seems that $domain is always original domain now.

Reversing to previous release, it's working ok now.

**Comment by c266** [comment]
I confirm. Same issue.

**Comment by straube** [comment]
Hey @kokers, thanks for reporting that. Could you send me a screenshot of your current plugin set up? Also, what's the domain you originally installed WordPress in?

**Comment by straube** [comment]
Hi! I saw the setup for a different installation and pushed a fix base on it. Could you give `0.10.2` a try and let me know whether it fixes your setup.

**Comment by kokers** [comment]
Sorry for late response, just got some time to test it and it's looking good! 👍 can't find any issues. Thanks! Really appreciate it :o)

**Comment by c266** [comment]
thank you
