### ISSUE TITLE
I can't get rid of the "path" 

### ISSUE THREAD

**Issue by mc9625** [straube/multiple-domain#46]
If I do redirect:
example.com/path to path.example.com when I open http://path.example.com I get: http://path.example.com/path  

Why?

**Comment by straube** [comment]
@mc9625 I ran some tests and that wasn't supposed to happen.

I need more info to help you debug that. Where are you making the redirect? Is it on the web server (nginx, Apache, etc) level? In any way, could you elaborate on how you're doing that?

**Comment by straube** [comment]
@mc9625 I'm wondering if you set `/path` as the base path restriction for `path.example.com`. Is that what you're doing?

**Comment by straube** [comment]
Closing this issue since I haven't heard back from @mc9625 for over a month.
