### ISSUE TITLE
WP Compatibility 5.1.1

### ISSUE THREAD

**Issue by kernig** [straube/multiple-domain#48]
On the addon page it says that the compatibility is tested up to wp 5.1.0.
When will the current version be compatible with 5.1.1?
https://wordpress.org/plugins/multiple-domain/

Thanks!

**Comment by straube** [comment]
Unfortunately, I haven't had much free time to work on the plugin lately. That's why it's not fully tested up to the latest release.

However, since 5.1.1 is just a bug fix release upon 5.1.0, I'd say it's already compatible. Have you found any incompatibilities?

**Comment by kernig** [comment]
I didn't mean to rush you. Just thought that it has been forgotten.
No, everything works as expected. Thank you for your effort!

**Comment by axlrho** [comment]
I'm with WP 5.1.1. and when I try to activate I get this:
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /public_html/wp-content/plugins/multiple-domain/multiple-domain.php on line 35

**Comment by straube** [comment]
What PHP version are you running? I guess you're running 5.4, which doesn't support the `::class` keyword.

**Comment by axlrho** [comment]
You are completely right. Thanks.

**Comment by straube** [comment]
The compatibility tag was updated.
