### ISSUE TITLE
replaceUrl too greedy when one domain is a prefix of another

### ISSUE THREAD

**Issue by cschleiden** [straube/multiple-domain#49]
My original url was `xxx.de` and now I've setup a second domain `xxx.dev`. Now it looks like `replaceDomain` is either sometimes called twice on urls *or* called on urls that already use the new domain. 

This resulted in some older posts, having the `srcset` attribute for images pointing to `xxx.devv` (notice the second `v`), since `replaceDomain` seems to have been applied to a `xxx.dev/wp-uploads/...` url trying to replace `xxx.de` with `xxx.dev` 

As a quick local workaround I've added the `/` to the regex and replacement string, but probably needs a bit more thought:

```php
$regex = '/(https?):\/\/' . preg_quote($domain) . '\//i';
$protocol = $this->getDomainProtocol($this->domain);
$replace = ($protocol === 'auto' ? '${1}' : $protocol) . '://' . $this->domain . '/';
```

**Comment by straube** [comment]
Hey @cschleiden. I noticed a similar issue and wrote a fix for it but didn't push to WP repository yet. Check this out: https://github.com/straube/multiple-domain/commit/1d6de1b04b73e4d696f3debb90477b17959be31a. Do you think it might fix the bug you found?

**Comment by straube** [comment]
Version 0.11.0 was released and include the mentioned fix.

**Comment by cschleiden** [comment]
Great! Sorry, I didn't get to test the fix from https://github.com/straube/multiple-domain/commit/1d6de1b04b73e4d696f3debb90477b17959be31a, I'll upgrade to the new version though and validate.
