### ISSUE TITLE
how can enable this plugin with .env file i'm use bedrock Wordpress installation 

### ISSUE THREAD

**Issue by ahmed-abdelaziz-rabea** [straube/multiple-domain#5]
Dears,
I'm installed this plugin on my WordPress site and I need active it but my Wordpress based on Bedrock WordPress installation you have any suggestions

**Comment by straube** [comment]
Hi!

I've never worked with this Bedrock Wordpress, but it seems you can use `wp-cli` to install plugins: https://discourse.roots.io/t/does-bedrock-trellis-disable-the-ability-to-add-install-plugins-via-admin/6925/3

Please let me know if that doesn't work for you. Also, if we should update the plugin in some specific way to support Bedrock, I appreciate if you tell me how.

**UPDATE**

It seems you can also add the plugin to your `composer.json` file, as you'd do for other composer deps, but setting a specific repository path: https://discourse.roots.io/t/best-way-to-install-private-paid-plugins-with-composer/1045/3

**Comment by straube** [comment]
@AhmedAbdelazizRabea Have something I mentioned in the previous comment worked for you?

**Comment by straube** [comment]
@AhmedAbdelazizRabea since I didn't hear back from you, I'm closing this issue. If you need further help, feel free to comment.

**Comment by ahmed-abdelaziz-rabea** [comment]
Dear,
Sorry for the delay, and thank you for your effort, but I ask how to add this in .env file
however, I used this code in config/application.php it's working fine now 

 define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME']. '/wp');
 define('WP_HOME', 'http://' . $_SERVER['SERVER_NAME']);


Thank you,
