### ISSUE TITLE
Website inaccessible after update to version 0.11.0

### ISSUE THREAD

**Issue by tobeyfox** [straube/multiple-domain#50]
Warning: strpos(): Empty needle in /www/wp-content/plugins/multiple-domain/MultipleDomain.php on line 418

**Comment by sooslaca** [comment]
+1 same here

AH01071: Got error 'PHP message: PHP Warning:  strpos(): Empty needle in /storage/vhost_default/htdocs/public_html/wp-content/plugins/multiple-domain/MultipleDomain.php on line 418'

**Comment by straube** [comment]
Hey! You're probably using `/` as base path for some domains, correct? If that's the case, the just released version 0.11.1 should fix that PHP error. No configuration change is required. You may keep using `/` as base path.

**Comment by sooslaca** [comment]
awesome, thanks @straube it works as expected ! and yes that's the case I use `/` as base path.
