### ISSUE TITLE
How to disable hreflang tags output even for the original domain?

### ISSUE THREAD

**Issue by straube** [straube/multiple-domain#51]
You may notice that even if you don't set a language for any domain, you still get a default `hreflang` tag in your page head. To disable this behavior, you can remove the action that adds that tag. To do so, add the following code to your theme's `functions.php` file:

```
function remove_multipledomain_hreflang()
{
    if (!class_exists('MultipleDomain')) {
        return;
    }
    $multipleDomain = MultipleDomain::instance();
    remove_action('wp_head', array($multipleDomain, 'addHrefLangHeader'));	
}

add_action('init', 'remove_multipledomain_hreflang');
```

**Comment by mytran** [comment]
For anyone looking to use this: `addHrefLangHeader` got renamed to `addHrefLangTags`

**Comment by straube** [comment]
Thanks @mytran for the heads up. I forgot about this issue when changed the action name.

**Comment by jklovance** [comment]
The solution does not work. The action 'addHrefLangHeader' is added several times during the render and only removed once. The tags are still there. I had to edit out the code that creates the tags to get rid of them. Do you have a hook that fires after the class is instantiated?
