### ISSUE TITLE
Hide base URL

### ISSUE THREAD

**Issue by straube** [straube/multiple-domain#52]
There are 2 requests on WP Support Forum for a new feature that enables base URL hiding:

* https://wordpress.org/support/topic/hide-base-url/
* https://wordpress.org/support/topic/all-links-redirect-to-domain-home-page/

This would require some extra work in the rewriting and redirection rules.

Any help on this development is appreciated.

**Comment by Tobias-Keller** [comment]
@straube trying to understand what exactly the problem is...can you explain it in more detail?

**Comment by straube** [comment]
This is not an actual issue. Some users asked for a way to remove the page name from the URL when a path restriction is in place. For example, get the following setup:

```
1
    Domain: example.com
    Base path: (no path restriction)

2
    Domain: other.org
    Base path: /some-page
```

Now, when a visitor access `http://other.org` they'll be redirected to `http://other.org/some-page`. The redirect happens due to the path restriction. This will also happen if the visitor points the browser to e.g. `http://other.org/other-link`. You can see the related logic [here, at line 477](https://github.com/straube/multiple-domain/blob/master/multiple-domain/MultipleDomain.php#L477).

Considering the example above, the (optional) feature would allow visitors accessing `http://other.org` to stay in that URL but viewing the contents of `http://other.org/some-page`.

I know this is not a simple feature. It also has some limitations, such as visitors would only see a single page in a given domain. What are your thoughts?

**Comment by Tobias-Keller** [comment]
I have to think about it ... and try a bit

**Comment by straube** [comment]
@Tobias-Keller I'm reconsidering this feature. It's not something a lot of users asked for and I also think it's a bit far from the plugin's main purpose, which is simply add support to multiple domains. A more complex setup like the one requested here can probably be achieved with [Wordpress Multisite](https://wordpress.org/support/article/create-a-network/).

I'm marking it as **wontfix**. If you by any chance started working on it, let me know and I can re-open the issue.
