### ISSUE TITLE
admin_url() return main domain url since 0.11

### ISSUE THREAD

**Issue by c266** [straube/multiple-domain#55]
update 0.11.0 (or 0.11.1) broke my site and i found the issue
I use this to set ajax url : 
wp_localize_script( 'jquery', 'MyAjax', array( 'ajaxurl' => admin_url( 'admin-ajax.php' ) ) );

but admin_url() is now returning main site url
(my site setup is complicated, with logged-in users being attached to a specific domain)

**Comment by straube** [comment]
Hey @crmb. Thanks for reporting that. Do you know the version you have installed before the update?

**Comment by c266** [comment]
It was working with 0.10.3

**Comment by straube** [comment]
@crmb I just released a new version that should fix this issue. It's **0.11.2**. Please let me know how it goes.

**Comment by c266** [comment]
Yes it's fixed thanks.
