### ISSUE TITLE
Question: Are wp-admin URLs replaced?

### ISSUE THREAD

**Issue by andyadams** [straube/multiple-domain#65]
Hello, just a question: I'd like users to be able to login to the WP Dashboard under a separate (non-siteurl) domain, but I noticed that `multiple-domain` doesn't adjust URLs if they contain `wp-admin` - is that correct? (Looking at [this line](https://github.com/straube/multiple-domain/blob/master/multiple-domain/MultipleDomain.php#L517))

If so, was there a reason this limitation is in effect? For example: will the WP Admin break if you use a non-siteurl domain? Or could I theoretically remove this restriction for my case?

Thank you in advance!

**Comment by straube** [comment]
Yeah, every admin URL bypasses the replacement logic. We had several users reporting issues related to admin URLs being rewritten, so the feature was removed.

You can try to remove that restriction and see how it goes in your case but I'd advise you to do that in a separate/testing environment. It may block the access to your site admin.

Let me know how it goes. If you're able to successfully remove the restriction I can add this feature as an option to the plugin settings.

**Comment by andyadams** [comment]
Thank you @straube ! In our case, I advised the team against it - we have a large site with multiple admin users, and the risk of breakage outweighed the benefits. Your timely response really helped a lot! Thank you.
