### ISSUE TITLE
Not currently working. 

### ISSUE THREAD

**Issue by stik2** [straube/multiple-domain#7]
I have pointed my domains to the same IP address of my WP Server. I installed the plugin and address my two other domain names and the folders in which they land on. But when I type in the address I am getting a 404 error from the WP server. The instructions are simple enough to set this up but it doesn't seem to be working.

**Comment by straube** [comment]
Hey @stik2 , sorry for the delayed response. Were you able to figure out this problem? If you weren't, please let me know how your config looks like so I can try to help fix it.

**Comment by straube** [comment]
Since this issue has 1+ month and I got no feedback from @stik2, I'm closing it.
