### ISSUE TITLE
Fix URI generated for canonical tag

### ISSUE THREAD

**Issue by mxgnr** [straube/multiple-domain#76]
Hi there,

First of all, thanks for making this useful plugin which i'm currently using for a project. 

My main concern was about the canonical tag generated by the plugin, since i figured out that it is not working properly with my WP domain configuration :

- Main domain of the WP instance : 
`https://www.example.com/some-subfolder/ ` ( this is actually the value returned by `home_url()` )
- Other domain added via the multi-domain plugin settings : 
`https://subdomain.example.com/some-subfolder/`

The other domain is working properly with this plugin, but when i browse to a category for example and i check the canonical URL generated by the plugin, it will display :
- `<link rel="canonical" href="https://www.example.com/category/my-category/" />` 
- instead of `<link rel="canonical" href="https://www.example.com/some-subfolder/category/my-category/" />`.

I've tried some changes by setting the URI according to `home_url()` WP configuration instead of making it from scratch as it is currently, which seems to be working but might need some additional tests. (See #75)

Feel free to check if you can confirm this issue.

**Comment by straube** [comment]
Hey @maxgranier, thanks for your contribution! I'll try to test it over this coming weekend and I let you know if there is any issue. Otherwise, I'll go ahead and merge your PR.

**Comment by straube** [comment]
@maxgranier The changes you made were finally released in version 1.0.6.
